# Configuration pour le Scraper Node US (Virginia)
app = 'scraper-us'
primary_region = 'iad'

[build]
[build.args]
NEXT_PUBLIC_SUPABASE_URL = "https://gmumhsqlewekjlrdsmgf.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtdW1oc3FsZXdla2pscmRzbWdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NzcwOTYsImV4cCI6MjA3NDI1MzA5Nn0.dxUKRE3tctiaHgyXmJTm4MmcCLMgVRjRLhsSuzTxgkI"
NEXT_PUBLIC_API_SECRET = "vinted_scraper_secure_2024"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['scraper']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  processes = ['scraper']

[processes]
  scraper = "npm start"

